### PR TITLE
Abstract Install command

### PR DESCRIPTION
**Pull request by xepozz**
I've tried to remove hardlink to `yiisoft` vendor while searching symlinks and added some abstraction for searching dependent packages while relinking.

### CODE REVIEW

**Comment by rugabarbo** [comment]
@xepozz what are the reasons for these changes? Currently, only **yiisoft** packages are processed by the tool.

I've seen #90, which is a good idea. But it cannot be solved so easily. 

To adapt to other vendors, you need to do:
* more flexible configurations
* extensible command loader
* plugin system
* rewrite documentation
* another tool name
* etc.

This is a big, complex work. It is better to do it in a separate repository. If we start this work here, it will be a mess. Now in the implementation a lot is binded to a specific vendor "yiisoft".

We can accidentally break a working tool by trying to unbind it, so there must be a good reason for such changes.

**Comment by xepozz** [comment]
No I don't agree with you.

> Now in the implementation a lot is binded to a specific vendor "yiisoft".

It's not true. 

> To adapt to other vendors, you need to do:

- more flexible configurations **<-- this PR for it**
- extensible command loader **<-- it's not needed now**
- plugin system **<-- it's not needed now**
- rewrite documentation **<-- it's not needed now**
- another tool name **<-- it's not needed now**
- etc. **<-- :)**

By the small steps we can adapt this package to work with other vendors. It's not as complicated as seems.

Anyway this PR doesn't increase complexity.

**Comment by rugabarbo** [comment]
@xepozz it seems that we are talking about different things. 

Do you just want to handle different vendors within the development of the framework?

Or do you want to work with the tool from under other projects?

**Comment by xepozz** [comment]
The second question is a special case of the  first question.
I'm talking about the first case.

**Comment by samdark** [comment]
The refactoring itself looks OK. @xepozz have you tried that in action?

**Comment by xepozz** [comment]
I tested this PR. Looks like worked :))

telegram-cloud-photo-size-2-5237742858792973427-y

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Need to add that to docs.

**Pull request merged**
