### PR TITLE
Add parallel runs

### PR DESCRIPTION
**Pull request by xepozz**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

There is result to call `time ./yii-dev install` on fully updated packages:

**branch:master**
```
real    2m6,023s
user    1m14,334s
sys     0m21,205s
```

**branch:parallels**
```
real    1m0,149s
user    2m20,763s
sys     0m50,069s
```

So the second branch 2 times faster, but now our commands not adapted to parallel runs :(

If anybody wants to continue work on it welcome to contribute. I don't have a lot of time to fix bugs.

### CODE REVIEW

**Comment by rugabarbo** [comment]
Thanks for the draft! I've tried parallelization before but got stopped by some issues of cross-platform support. This is a difficult task. It requires extensive testing.

**Comment by xepozz** [comment]
We can try to make emulated environment like in [composer-config-plugin](https://github.com/yiisoft/composer-config-plugin/tree/master/tests/Integration/Environment)

**Comment by rugabarbo** [comment]
In fact, we can implement parallelization without using additional libraries. Symfony processes support asynchronous execution. It might look something like this:

```
        use Symfony\Component\Process\Process;
        
        $commands = [];
        $processes = [];
        
        // Init process objects
        foreach($commands as $command){
            $processes[] = new Process($command);
        }

        // Start processes
        foreach($processes as $process){
            $process->start();
        }

        // Wait for the every process
        foreach($processes as $process){
            $process->wait();
        }
```

The problem is in the implementation. There is a lot to consider.

**Comment by samdark** [comment]
Can't be merged in its current state.

**Pull request closed without merging**
