### PR TITLE
Use vendor name everywhere and remove setting to upstream repository.

### PR DESCRIPTION
**Pull request by DAGpro**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️

If the last 3 pull requests pass, there will be no need to set up an upstream repository

### CODE REVIEW

**Comment by vjik** [comment]
@DAGpro Which PRs are meant?

**Comment by DAGpro** [comment]
#226 at the heart of this PR, others unnecessarily mentioned

**Comment by samdark** [comment]
@DAGpro is this one cleaning up code that is now unnecessary?

**Comment by DAGpro** [comment]
@samdark 

With the ability to configure the owner in the dev tool for all packages and the ability to synchronize them with the upstream repository, I think the code from this pull request is not needed.

In the dev tool, you can now easily work with fork repositories, if there is a need to install an upstream repository, it can be configured in packages.local and updated with update command

**Comment by samdark** [comment]
So... closing or merging?

**Comment by DAGpro** [comment]
> So... closing or merging?

merge, found no problems interfering with the merge

**Pull request merged**
