### PR TITLE
Group remove old dependencies

### PR DESCRIPTION
**Pull request by xepozz**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by rugabarbo** [comment]
Thanks for the idea. Is it for performance? 

As far as I remember, there were some nuances due to which I did not group the processing of symlinks.

**Comment by xepozz** [comment]
> Thanks for the idea. Is it for performance?

I didn't test it. I've only grouped it like `createSymbolicLinks`

**Comment by rugabarbo** [comment]
Unfortunately, this looks like a bad idea. Only those packages that are being processed should be removed. Otherwise, because of the installation of one package, everything is deleted. It doesn't make sense. And this is a dangerous operation (if the program is interrupted, we will be left without symlinks at all).

On the contrary, such operations should be ungrouped and made as compact as possible.

**Comment by xepozz** [comment]
I've fixed that.

**Comment by xepozz** [comment]
@rugabarbo As you said this PR does incorrect behavior. 
I'm closing this PR.

**Comment by rugabarbo** [comment]
> As you said this PR does incorrect behavior.

Yes...
Also I'll ungroup `createSymbolicLinks()` in the future. It'll be safer behavior.

Thanks for pointing this out.

**Pull request closed without merging**
