### PR TITLE
Relative symlinks for containerized environment

### PR DESCRIPTION
**Pull request by viktorprogger**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | ❌

### CODE REVIEW

**Comment by rugabarbo** [comment]
Looks like a hack... Is it possible to solve the problem using Docker settings?

**Comment by viktorprogger** [comment]
> Looks like a hack... Is it possible to solve the problem using Docker settings?

I didn't find any. The problem is in different absolute paths inside and outside a container. If symlinks are made in a container, they don't work on a host machine, and vise versa. Relative paths usage is the only decision I know.

**Comment by samdark** [comment]
That should be alright.

**Comment by samdark** [comment]
👍

**Pull request merged**
