### PR TITLE
Add sqlite3 for full support of yii-demo

### PR DESCRIPTION
**Pull request by Fantom409**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️/❌
| Breaks BC?    | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by rugabarbo** [comment]
Many packages have specific dependencies. Not everyone needs them. Installing all specific dependencies for all packages can lead to conflicts. I would not pre-install SQLite.

**Comment by rugabarbo** [comment]
@samdark what do you think about it? Should we pre-install all the specific dependencies for each package during the default installation? SQLite is specific dep.

**Comment by Fantom409** [comment]
> Many packages have specific dependencies. Not everyone needs them. Installing all specific dependencies for all packages can lead to conflicts. I would not pre-install SQLite.

We can make installing of specific dependencies optional via environment variables

**Comment by samdark** [comment]
I think it is OK to have it. That's a development tool and this pull request makes working with it better.

**Review by samdark — APPROVED** [review]

**Pull request merged**
